[package]
name = "scrob-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.12.2"
scrob-core = { path = "../scrob-core" }