name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
         - windows
         - ubuntu
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-node@v2

    - name: Generate Web Assets 
      shell: bash
      run: |
        cd web
        yarn install
        yarn run setup:dev 
        yarn run static
        yarn run build

    - name: Dependencies (Linux)
      if: matrix.os == 'ubuntu'
      run: sudo apt install libdbus-1-dev libpango1.0-dev libatk1.0-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev

    - name: Dependencies (Windows)
      if: matrix.os == 'windows'
      run: echo "nothing here"

    - name: Build (optimzed)
      env: 
        RUSTFLAGS: "-C link-arg=-s"
      run: |
        cargo build --release 
        mkdir _release
        mv target/release/scrob-* _release/.

    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: _release

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2

    - name: Create release and upload artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGELOG_TYPE: conventional
      run: |
        ls -alHR
        wget -q https://github.com/srevinsaju/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage && chmod +x pyuploadtool-x86_64.AppImage
        ./pyuploadtool-x86_64.AppImage \
          windows-release/* ubuntu-release/*
    
