name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
         - windows
         - ubuntu
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies (Linux)
      if: matrix.os == 'ubuntu'
      run: sudo apt install libdbus-1-dev libpango1.0-dev libatk1.0-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev

    - name: Dependencies (Windows)
      if: matrix.os == 'windows'
      run: echo "nothing here"


    - name: Build
      run: cargo build
    - name: Build (optimzed)
      run: |
        RUSTFLAGS='-C link-arg=-s' cargo build --release 
        mkdir _release
        mv target/release/lyrix-*

    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: _release

